version: '3'

services:
  app:
    image: hls-app
    build: .
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}  
    restart: on-failure:5
    volumes:
      - ./src:/usr/service/src  
    networks:
       - net  
      
  db:
    image: hls-db
    build: ./database
    restart: on-failure:5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/lib/postgresql/logs
    networks:
      - net  

volumes:
  postgres_data:
  postgres_logs:   

networks:
  net: 
    driver: bridge